site_name: Web-программирование

nav:
  - Главная: index.md
  - Лабораторные работы:
      - Лабораторная работа 1: lab1.md
      - Лабораторная работа 2: lab2.md
      - Лабораторная работа 3: lab3/intro.md
theme:
 name: cinder